#version 450
#pragma shader_stage(compute)

layout (local_size_x_id = 0, local_size_y_id = 1) in;

layout (binding = 0) uniform sampler2D inputImage;
layout (binding = 1, rgba8) uniform writeonly image2D outputImage;


void main() {
    vec3 inputPixel = texture(inputImage, vec2(gl_GlobalInvocationID.xy)).rgb;
    imageStore(outputImage, ivec2(gl_GlobalInvocationID.xy), vec4(inputPixel, 1.0f));
}
